---
#
- set_fact:
    service_name: oracle-database-11g

- name: define service
  template:
    src: oracle-database-11g.service.j2
    dest: /etc/systemd/system/{{ service_name }}.service

- name: enable service
  service: name={{ service_name }} enabled=yes
