---
#
- name: evaluate oracle database instance
  stat: path="{{ oracle_database_oracle_home }}/dbs/spfile{{ oracle_database_sid }}.ora"
  register: orafile
  become: yes
  become_user: oracle

- debug:
    msg: "an oracle instance is already installed with this sid {{ oracle_database_sid }}"
  when: orafile.stat.exists

- include: create-instance-11g.yml
  when: not orafile.stat.exists and oracle_database_version == '11g'
