---
#
- debug:
    var: oracle_database_version

- name: validate oracle database version is supported
  fail: "msg='version is not valid (supported versions: [11g])'"
  when: oracle_database_version is defined and oracle_database_version != '11g'

- name: validate oracle database is installed
  stat: path="{{ oracle_database_oracle_home }}/bin/sqlplus"
  register: sqlplus
  become: yes
  become_user: "root"

- debug:
    message: "oracle database is already installed in this {{ oracle_database_oracle_home }}"
  when: sqlplus.stat.exists

- include: install-db-11g.yml
  when: not sqlplus.stat.exists and oracle_database_version == '11g'
